/**
 * Traduce i nomi degli esercizi importati da free-exercise-db in italiano.
 * Aggiorna solo esercizi con nameIt == name (non ancora tradotti).
 * Esegui con:
 *   npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/translate-exercises.ts
 */
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// Mapping: nome inglese → nome italiano
const T: Record<string, string> = {
  // ── A ──────────────────────────────────────────────────────────────────────
  "3/4 Sit-Up": "Sit-up 3/4",
  "Ab Crunch Machine": "Crunch addominale alla macchina",
  "Ab Roller": "Ruota addominale",
  "Adductor": "Adduttori",
  "Adductor/Groin": "Adduttori/Inguine",
  "Advanced Kettlebell Windmill": "Windmill avanzato con kettlebell",
  "Air Bike": "Bici aerea",
  "Alternate Hammer Curl": "Curl a martello alternato",
  "Alternate Heel Touchers": "Tocchi ai talloni alternati",
  "Alternate Incline Dumbbell Curl": "Curl su panca inclinata alternato con manubri",
  "Alternate Leg Diagonal Bound": "Balzo diagonale a gamba alternata",
  "Alternating Cable Shoulder Press": "Press spalle ai cavi alternato",
  "Alternating Deltoid Raise": "Alzate deltoidi alternate",
  "Alternating Floor Press": "Press a terra alternato",
  "Alternating Hang Clean": "Hang clean alternato",
  "Alternating Kettlebell Press": "Press con kettlebell alternato",
  "Alternating Kettlebell Row": "Remata con kettlebell alternata",
  "Alternating Renegade Row": "Renegade row alternato",
  "Arnold Dumbbell Press": "Press Arnold con manubri",
  "Around The Worlds": "Giro del mondo",
  "Atlas Stone Trainer": "Trainer pietra atlas",
  "Atlas Stones": "Pietre atlas",
  "Axle Deadlift": "Stacco con axle bar",

  // ── B ──────────────────────────────────────────────────────────────────────
  "Back Flyes - With Bands": "Croci per schiena con elastici",
  "Backward Drag": "Trascinamento all'indietro",
  "Backward Medicine Ball Throw": "Lancio palla medica all'indietro",
  "Band Assisted Pull-Up": "Trazioni assistite con elastico",
  "Band Good Morning": "Good morning con elastico",
  "Band Good Morning (Pull Through)": "Good morning con elastico (pull through)",
  "Band Hip Adductions": "Adduzione anca con elastico",
  "Band Pull Apart": "Band pull-apart",
  "Band Skull Crusher": "Skull crusher con elastico",
  "Barbell Ab Rollout": "Rollout addominale con bilanciere",
  "Barbell Ab Rollout - On Knees": "Rollout addominale con bilanciere in ginocchio",
  "Barbell Bench Press - Medium Grip": "Panca piana con bilanciere presa media",
  "Barbell Curl": "Curl con bilanciere",
  "Barbell Curls Lying Against An Incline": "Curl con bilanciere su panca inclinata",
  "Barbell Deadlift": "Stacco da terra con bilanciere",
  "Barbell Full Squat": "Squat completo con bilanciere",
  "Barbell Glute Bridge": "Ponte glutei con bilanciere",
  "Barbell Guillotine Bench Press": "Panca guillotine con bilanciere",
  "Barbell Hack Squat": "Hack squat con bilanciere",
  "Barbell Hip Thrust": "Hip thrust con bilanciere",
  "Barbell Incline Bench Press - Medium Grip": "Panca inclinata con bilanciere presa media",
  "Barbell Incline Shoulder Raise": "Alzata spalle su panca inclinata con bilanciere",
  "Barbell Lunge": "Affondi con bilanciere",
  "Barbell Rear Delt Row": "Remata bilanciere per deltoide posteriore",
  "Barbell Rollout from Bench": "Rollout con bilanciere dalla panca",
  "Barbell Seated Calf Raise": "Calf raise seduto con bilanciere",
  "Barbell Shoulder Press": "Press spalle con bilanciere",
  "Barbell Shrug": "Scrollata di spalle con bilanciere",
  "Barbell Shrug Behind The Back": "Scrollata di spalle con bilanciere dietro la schiena",
  "Barbell Side Bend": "Flessione laterale con bilanciere",
  "Barbell Side Split Squat": "Squat split laterale con bilanciere",
  "Barbell Squat": "Squat con bilanciere",
  "Barbell Squat To A Bench": "Squat con bilanciere verso panca",
  "Barbell Step Ups": "Step-up con bilanciere",
  "Barbell Walking Lunge": "Affondi in cammino con bilanciere",
  "Battling Ropes": "Battle ropes",
  "Bear Crawl Sled Drags": "Trascinamento slitta in quadrupedia",
  "Bench Dips": "Dip alla panca",
  "Bench Jump": "Salto sulla panca",
  "Bench Press - Powerlifting": "Panca piana (powerlifting)",
  "Bench Press - With Bands": "Panca piana con elastici",
  "Bench Press with Chains": "Panca piana con catene",
  "Bent Over Barbell Row": "Remata con bilanciere busto inclinato",
  "Bent Over Dumbbell Rear Delt Raise With Head On Bench": "Alzate posteriori con manubri busto inclinato",
  "Bent Over Low-Pulley Side Lateral": "Alzate laterali al cavo basso busto inclinato",
  "Bent Over One-Arm Long Bar Row": "Remata monobraccio con bilanciere lungo busto inclinato",
  "Bent Over Two-Arm Long Bar Row": "Remata bibraccio con bilanciere lungo busto inclinato",
  "Bent Over Two-Dumbbell Row": "Remata con due manubri busto inclinato",
  "Bent Over Two-Dumbbell Row With Palms In": "Remata con manubri palmi verso l'interno",
  "Bent Press": "Bent press",
  "Bent-Arm Barbell Pullover": "Pullover con bilanciere braccia piegate",
  "Bent-Arm Dumbbell Pullover": "Pullover con manubrio braccia piegate",
  "Bent-Knee Hip Raise": "Sollevamento anca a ginocchio piegato",
  "Bicycling": "Ciclismo",
  "Bicycling, Stationary": "Bici stazionaria",
  "Board Press": "Board press",
  "Body Tricep Press": "Press tricipiti a corpo libero",
  "Body-Up": "Body-up",
  "Bodyweight Flyes": "Croci a corpo libero",
  "Bodyweight Mid Row": "Remata media a corpo libero",
  "Bodyweight Squat": "Squat a corpo libero",
  "Bodyweight Walking Lunge": "Affondi in cammino a corpo libero",
  "Bottoms Up": "Bottoms up",
  "Bottoms-Up Clean From The Hang Position": "Clean dalla posizione di hang con kettlebell capovolto",
  "Box Jump (Multiple Response)": "Box jump (risposta multipla)",
  "Box Skip": "Skip sul box",
  "Box Squat": "Box squat",
  "Box Squat with Bands": "Box squat con elastici",
  "Box Squat with Chains": "Box squat con catene",
  "Bradford/Rocky Presses": "Bradford press",
  "Butt Lift (Bridge)": "Ponte glutei",
  "Butt-Ups": "Butt-up",
  "Butterfly": "Butterfly",

  // ── C ──────────────────────────────────────────────────────────────────────
  "Cable Chest Press": "Press petto ai cavi",
  "Cable Crossover": "Croci ai cavi",
  "Cable Crunch": "Crunch ai cavi",
  "Cable Deadlifts": "Stacco da terra ai cavi",
  "Cable Hammer Curls - Rope Attachment": "Curl a martello ai cavi con corda",
  "Cable Hip Adduction": "Adduzione anca al cavo",
  "Cable Incline Pushdown": "Pushdown al cavo su panca inclinata",
  "Cable Incline Triceps Extension": "Estensione tricipiti al cavo su panca inclinata",
  "Cable Internal Rotation": "Rotazione interna al cavo",
  "Cable Iron Cross": "Croce di ferro al cavo",
  "Cable Lying Triceps Extension": "Estensione tricipiti al cavo sdraiato",
  "Cable One Arm Tricep Extension": "Estensione tricipiti monobraccio al cavo",
  "Cable Preacher Curl": "Curl al cavo su panca scott",
  "Cable Rear Delt Fly": "Croci posteriori al cavo",
  "Cable Reverse Crunch": "Crunch inverso al cavo",
  "Cable Rope Overhead Triceps Extension": "Estensione tricipiti sopra la testa con corda al cavo",
  "Cable Rope Rear-Delt Rows": "Remata posteriore con corda al cavo",
  "Cable Russian Twists": "Russian twist al cavo",
  "Cable Seated Crunch": "Crunch seduto al cavo",
  "Cable Seated Lateral Raise": "Alzata laterale seduto al cavo",
  "Cable Shoulder Press": "Press spalle al cavo",
  "Cable Shrugs": "Scrollata di spalle al cavo",
  "Cable Wrist Curl": "Curl polso al cavo",
  "Calf Press": "Press polpacci",
  "Calf Press On The Leg Press Machine": "Calf raise alla leg press",
  "Calf Raise On A Dumbbell": "Calf raise con manubrio",
  "Calf Raises - With Bands": "Calf raise con elastici",
  "Calf-Machine Shoulder Shrug": "Scrollata di spalle alla macchina calf",
  "Car Deadlift": "Stacco auto",
  "Car Drivers": "Car drivers",
  "Chair Squat": "Squat sulla sedia",
  "Chin-Up": "Trazioni presa supina",
  "Circus Bell": "Circus bell",
  "Clean": "Clean",
  "Clean Deadlift": "Stacco per il clean",
  "Clean Pull": "Clean pull",
  "Clean Shrug": "Scrollata di spalle per il clean",
  "Clean and Jerk": "Clean and jerk",
  "Clean and Press": "Clean and press",
  "Clean from Blocks": "Clean dai blocchi",
  "Clock Push-Up": "Flessioni a orologio",
  "Close-Grip Barbell Bench Press": "Panca piana presa stretta con bilanciere",
  "Close-Grip Dumbbell Press": "Press presa stretta con manubri",
  "Close-Grip EZ Bar Curl": "Curl presa stretta con bilanciere EZ",
  "Close-Grip EZ-Bar Curl with Band": "Curl presa stretta con bilanciere EZ ed elastico",
  "Close-Grip EZ-Bar Press": "Press presa stretta con bilanciere EZ",
  "Close-Grip Front Lat Pulldown": "Lat machine presa stretta anteriore",
  "Close-Grip Push-Up off of a Dumbbell": "Flessioni presa stretta su manubri",
  "Close-Grip Standing Barbell Curl": "Curl in piedi presa stretta con bilanciere",
  "Cocoons": "Cocoon",
  "Concentration Curls": "Curl concentrato",
  "Cross Body Hammer Curl": "Curl a martello incrociato",
  "Cross Over - With Bands": "Crossover con elastici",
  "Cross-Body Crunch": "Crunch incrociato",
  "Crossover Reverse Lunge": "Affondo inverso incrociato",
  "Cuban Press": "Cuban press",
  "Dead Bug": "Dead bug",
  "Deadlift with Bands": "Stacco da terra con elastici",
  "Deadlift with Chains": "Stacco da terra con catene",
  "Decline Barbell Bench Press": "Panca declinata con bilanciere",
  "Close-Grip Decline Bench To Skull Crusher": "Panca declinata presa stretta fino allo skull crusher",
  "Decline Close-Grip Bench To Skull Crusher": "Panca declinata presa stretta fino allo skull crusher",
  "Decline Crunch": "Crunch su panca declinata",
  "Decline Dumbbell Bench Press": "Panca declinata con manubri",
  "Decline Dumbbell Flyes": "Croci su panca declinata con manubri",
  "Decline Dumbbell Triceps Extension": "Estensione tricipiti su panca declinata con manubri",
  "Decline EZ Bar Triceps Extension": "Estensione tricipiti su panca declinata con bilanciere EZ",
  "Decline Oblique Crunch": "Crunch obliquo su panca declinata",
  "Decline Push-Up": "Flessioni declinat",
  "Decline Reverse Crunch": "Crunch inverso su panca declinata",
  "Decline Smith Press": "Panca declinata alla Smith machine",
  "Deficit Deadlift": "Stacco in deficit",
  "Depth Jump Leap": "Salto in profondità",
  "Dip Machine": "Dip alla macchina",
  "Dips - Chest Version": "Dip per il petto",
  "Dips - Triceps Version": "Dip per i tricipiti",
  "Donkey Calf Raises": "Calf raise asino",
  "Double Kettlebell Alternating Hang Clean": "Hang clean alternato con due kettlebell",
  "Double Kettlebell Jerk": "Jerk con due kettlebell",
  "Double Kettlebell Push Press": "Push press con due kettlebell",
  "Double Kettlebell Snatch": "Snatch con due kettlebell",
  "Double Kettlebell Windmill": "Windmill con due kettlebell",
  "Double Leg Butt Kick": "Calcio ai glutei bipodalico",
  "Drag Curl": "Drag curl",
  "Dumbbell Alternate Bicep Curl": "Curl bicipiti alternato con manubri",
  "Dumbbell Bench Press": "Panca piana con manubri",
  "Dumbbell Bench Press with Neutral Grip": "Panca piana con manubri presa neutra",
  "Dumbbell Bicep Curl": "Curl bicipiti con manubri",
  "Dumbbell Clean": "Clean con manubri",
  "Dumbbell Floor Press": "Press a terra con manubri",
  "Dumbbell Flyes": "Croci con manubri",
  "Dumbbell Incline Row": "Remata inclinata con manubri",
  "Dumbbell Incline Shoulder Raise": "Alzata spalle inclinata con manubri",
  "Dumbbell Lunges": "Affondi con manubri",
  "Dumbbell Lying One-Arm Rear Lateral Raise": "Alzata laterale posteriore monobraccio con manubrio sdraiato",
  "Dumbbell Lying Pronation": "Pronazione con manubrio sdraiato",
  "Dumbbell Lying Rear Lateral Raise": "Alzata laterale posteriore con manubri sdraiato",
  "Dumbbell Lying Supination": "Supinazione con manubrio sdraiato",
  "Dumbbell One-Arm Shoulder Press": "Press spalle monobraccio con manubrio",
  "Dumbbell One-Arm Triceps Extension": "Estensione tricipiti monobraccio con manubrio",
  "Dumbbell One-Arm Upright Row": "Remata verticale monobraccio con manubrio",
  "Dumbbell Prone Incline Curl": "Curl su panca inclinata prono con manubri",
  "Dumbbell Raise": "Alzata con manubrio",
  "Dumbbell Rear Lunge": "Affondo posteriore con manubri",
  "Dumbbell Scaption": "Scaption con manubri",
  "Dumbbell Seated Box Jump": "Box jump seduto con manubri",
  "Dumbbell Seated One-Leg Calf Raise": "Calf raise monopodalico seduto con manubrio",
  "Dumbbell Shoulder Press": "Press spalle con manubri",
  "Dumbbell Shrug": "Scrollata di spalle con manubri",
  "Dumbbell Side Bend": "Flessione laterale con manubrio",
  "Dumbbell Squat": "Squat con manubri",
  "Dumbbell Squat To A Bench": "Squat verso panca con manubri",
  "Dumbbell Step Ups": "Step-up con manubri",
  "Dumbbell Tricep Extension -Pronated Grip": "Estensione tricipiti con manubri presa pronata",

  // ── E ──────────────────────────────────────────────────────────────────────
  "EZ-Bar Curl": "Curl con bilanciere EZ",
  "EZ-Bar Skullcrusher": "Skull crusher con bilanciere EZ",
  "Elevated Back Lunge": "Affondo posteriore elevato",
  "Elevated Cable Rows": "Remata al cavo alta",
  "Elliptical Trainer": "Ellittica",
  "Exercise Ball Crunch": "Crunch sulla palla fitness",
  "Exercise Ball Pull-In": "Pull-in sulla palla fitness",
  "Extended Range One-Arm Kettlebell Floor Press": "Press a terra monobraccio con kettlebell ampiezza estesa",
  "External Rotation": "Rotazione esterna",
  "External Rotation with Band": "Rotazione esterna con elastico",
  "External Rotation with Cable": "Rotazione esterna al cavo",

  // ── F ──────────────────────────────────────────────────────────────────────
  "Face Pull": "Face pull",
  "Farmer's Walk": "Farmer's walk",
  "Fast Skipping": "Salto con la corda veloce",
  "Finger Curls": "Curl delle dita",
  "Flat Bench Cable Flyes": "Croci ai cavi su panca piana",
  "Flat Bench Leg Pull-In": "Pull-in gambe su panca piana",
  "Flat Bench Lying Leg Raise": "Alzata gambe sdraiato su panca piana",
  "Flexor Incline Dumbbell Curls": "Curl su panca inclinata flessore con manubri",
  "Floor Glute-Ham Raise": "Glutei-femorali a terra",
  "Floor Press": "Press a terra",
  "Floor Press with Chains": "Press a terra con catene",
  "Flutter Kicks": "Flutter kicks",
  "Forward Drag with Press": "Trascinamento in avanti con press",
  "Frankenstein Squat": "Frankenstein squat",
  "Freehand Jump Squat": "Jump squat a corpo libero",
  "Frog Hops": "Salti rana",
  "Frog Sit-Ups": "Sit-up a rana",
  "Front Barbell Squat": "Squat frontale con bilanciere",
  "Front Barbell Squat To A Bench": "Squat frontale con bilanciere verso panca",
  "Front Box Jump": "Box jump frontale",
  "Front Cable Raise": "Alzata frontale al cavo",
  "Front Dumbbell Raise": "Alzata frontale con manubri",
  "Front Incline Dumbbell Raise": "Alzata frontale inclinata con manubri",
  "Front Leg Raises": "Alzata frontale gambe",
  "Front Plate Raise": "Alzata frontale con disco",
  "Front Raise And Pullover": "Alzata frontale e pullover",
  "Front Squat (Clean Grip)": "Squat frontale (presa clean)",
  "Front Squats With Two Kettlebells": "Squat frontale con due kettlebell",
  "Front Two-Dumbbell Raise": "Alzata frontale con due manubri",
  "Full Range-Of-Motion Lat Pulldown": "Lat machine a piena escursione",

  // ── G ──────────────────────────────────────────────────────────────────────
  "Glute Ham Raise": "Glutei-femorali raise",
  "Glute Kickback": "Kickback glutei",
  "Goblet Squat": "Goblet squat",
  "Good Morning": "Good morning",
  "Good Morning off Pins": "Good morning dai pin",
  "Gorilla Chin/Crunch": "Gorilla chin/crunch",
  "Groiners": "Groiners",
  "Hack Squat": "Hack squat",
  "Hammer Curls": "Curl a martello",
  "Hammer Grip Incline DB Bench Press": "Panca inclinata con manubri presa a martello",
  "Handstand Push-Ups": "Flessioni in verticale",
  "Hang Clean": "Hang clean",
  "Hang Clean - Below the Knees": "Hang clean sotto le ginocchia",
  "Hang Snatch": "Hang snatch",
  "Hang Snatch - Below Knees": "Hang snatch sotto le ginocchia",
  "Hanging Bar Good Morning": "Good morning appeso alla sbarra",
  "Hanging Leg Raise": "Alzata gambe alla sbarra",
  "Hanging Pike": "Pike appeso",
  "Heaving Snatch Balance": "Heaving snatch balance",
  "High Cable Curls": "Curl al cavo alto",
  "Hip Extension with Bands": "Estensione anca con elastici",
  "Hip Flexion with Band": "Flessione anca con elastico",
  "Hip Lift with Band": "Sollevamento anca con elastico",
  "Hurdle Hops": "Salti sugli ostacoli",
  "Hyperextensions (Back Extensions)": "Iperestensioni (estensioni schiena)",
  "Hyperextensions With No Hyperextension Bench": "Iperestensioni senza panca",

  // ── I ──────────────────────────────────────────────────────────────────────
  "Inchworm": "Inchworm",
  "Incline Barbell Triceps Extension": "Estensione tricipiti su panca inclinata con bilanciere",
  "Incline Bench Pull": "Remata su panca inclinata",
  "Incline Cable Chest Press": "Press petto su panca inclinata al cavo",
  "Incline Cable Flye": "Croci su panca inclinata al cavo",
  "Incline Dumbbell Bench With Palms Facing In": "Panca inclinata con manubri palmi verso l'interno",
  "Incline Dumbbell Curl": "Curl su panca inclinata con manubri",
  "Incline Dumbbell Flyes": "Croci su panca inclinata con manubri",
  "Incline Dumbbell Flyes - With A Twist": "Croci su panca inclinata con rotazione",
  "Incline Dumbbell Press": "Press su panca inclinata con manubri",
  "Incline Hammer Curls": "Curl a martello su panca inclinata",
  "Incline Inner Biceps Curl": "Curl bicipiti interni su panca inclinata",
  "Incline Push-Up": "Flessioni su piano inclinato",
  "Incline Push-Up Close-Grip": "Flessioni inclinat presa stretta",
  "Incline Push-Up Depth Jump": "Flessioni inclinate in salto",
  "Incline Push-Up Medium": "Flessioni inclinate presa media",
  "Incline Push-Up Reverse Grip": "Flessioni inclinate presa inversa",
  "Incline Push-Up Wide": "Flessioni inclinate presa larga",
  "Internal Rotation with Band": "Rotazione interna con elastico",
  "Inverted Row": "Remata invertita",
  "Inverted Row with Straps": "Remata invertita con cinghie",
  "Iron Cross": "Croce di ferro",
  "Isometric Chest Squeezes": "Contrazione isometrica petto",
  "Isometric Wipers": "Tergicristalli isometrici",

  // ── J ──────────────────────────────────────────────────────────────────────
  "JM Press": "JM press",
  "Jackknife Sit-Up": "Sit-up jackknife",
  "Janda Sit-Up": "Sit-up Janda",
  "Jefferson Squats": "Jefferson squat",
  "Jerk Balance": "Jerk balance",
  "Jerk Dip Squat": "Squat con affondo jerk",
  "Jogging, Treadmill": "Jogging sul tapis roulant",

  // ── K ──────────────────────────────────────────────────────────────────────
  "Keg Load": "Carico barile",
  "Kettlebell Arnold Press": "Arnold press con kettlebell",
  "Kettlebell Dead Clean": "Dead clean con kettlebell",
  "Kettlebell Figure 8": "Figura 8 con kettlebell",
  "Kettlebell Hang Clean": "Hang clean con kettlebell",
  "Kettlebell One-Legged Deadlift": "Stacco monopodalico con kettlebell",
  "Kettlebell Pass Between The Legs": "Passaggio kettlebell tra le gambe",
  "Kettlebell Pirate Ships": "Navi pirata con kettlebell",
  "Kettlebell Pistol Squat": "Pistol squat con kettlebell",
  "Kettlebell Seated Press": "Press seduto con kettlebell",
  "Kettlebell Seesaw Press": "Press altalena con kettlebell",
  "Kettlebell Sumo High Pull": "Sumo high pull con kettlebell",
  "Kettlebell Thruster": "Thruster con kettlebell",
  "Kettlebell Turkish Get-Up (Lunge style)": "Turkish get-up con kettlebell (stile affondo)",
  "Kettlebell Turkish Get-Up (Squat style)": "Turkish get-up con kettlebell (stile squat)",
  "Kettlebell Windmill": "Windmill con kettlebell",
  "Kipping Muscle Up": "Kipping muscle-up",
  "Knee Tuck Jump": "Salto con ginocchia al petto",
  "Knee/Hip Raise On Parallel Bars": "Alzata ginocchia/anca alle parallele",
  "Kneeling Cable Crunch With Alternating Oblique Twists": "Crunch al cavo in ginocchio con torsioni oblique alternate",
  "Kneeling Cable Triceps Extension": "Estensione tricipiti al cavo in ginocchio",
  "Kneeling High Pulley Row": "Remata al cavo alto in ginocchio",
  "Kneeling Jump Squat": "Salto squat in ginocchio",
  "Kneeling Single-Arm High Pulley Row": "Remata monobraccio al cavo alto in ginocchio",
  "Kneeling Squat": "Squat in ginocchio",

  // ── L ──────────────────────────────────────────────────────────────────────
  "Landmine 180's": "Landmine 180°",
  "Landmine Linear Jammer": "Landmine jammer lineare",
  "Lateral Bound": "Balzo laterale",
  "Lateral Box Jump": "Box jump laterale",
  "Lateral Cone Hops": "Salti laterali sui coni",
  "Lateral Raise - With Bands": "Alzate laterali con elastici",
  "Leg Extensions": "Leg extension",
  "Leg Lift": "Alzata gambe",
  "Leg Press": "Leg press",
  "Leg Pull-In": "Pull-in gambe",
  "Leg-Over Floor Press": "Press a terra con gamba incrociata",
  "Leverage Chest Press": "Chest press alla macchina",
  "Leverage Deadlift": "Stacco alla macchina",
  "Leverage Decline Chest Press": "Chest press declinata alla macchina",
  "Leverage High Row": "Remata alta alla macchina",
  "Leverage Incline Chest Press": "Chest press inclinata alla macchina",
  "Leverage Iso Row": "Remata iso alla macchina",
  "Leverage Shoulder Press": "Press spalle alla macchina",
  "Leverage Shrug": "Scrollata di spalle alla macchina",
  "Log Lift": "Sollevamento tronco",
  "Low Cable Crossover": "Croci al cavo basso",
  "Low Cable Triceps Extension": "Estensione tricipiti al cavo basso",
  "Low Pulley Row To Neck": "Remata al cavo basso verso il collo",
  "Lower Back Curl": "Curl per la lombare",
  "Lunge Pass Through": "Affondo con passaggio",
  "Lunge Sprint": "Sprint con affondi",
  "Lying Cable Curl": "Curl al cavo sdraiato",
  "Lying Cambered Barbell Row": "Remata con bilanciere cambered sdraiato",
  "Lying Close-Grip Bar Curl On High Pulley": "Curl presa stretta al cavo alto sdraiato",
  "Lying Close-Grip Barbell Triceps Extension Behind The Head": "Estensione tricipiti dietro la testa con bilanciere presa stretta sdraiato",
  "Lying Close-Grip Barbell Triceps Press To Chin": "Press tricipiti verso il mento presa stretta sdraiato",
  "Lying Crossover": "Crossover sdraiato",
  "Lying Dumbbell Tricep Extension": "Estensione tricipiti con manubri sdraiato",
  "Lying Glute": "Stiramento gluteo sdraiato",
  "Lying Hamstring": "Stretching femorali sdraiato",
  "Lying High Bench Barbell Curl": "Curl su panca alta sdraiato con bilanciere",
  "Lying Leg Curls": "Leg curl sdraiato",
  "Lying Machine Squat": "Squat alla macchina sdraiato",
  "Lying One-Arm Lateral Raise": "Alzata laterale monobraccio sdraiato",
  "Lying Rear Delt Raise": "Alzata posteriori sdraiato",
  "Lying Supine Dumbbell Curl": "Curl supino con manubri sdraiato",
  "Lying T-Bar Row": "Remata T-bar sdraiato",
  "Lying Triceps Press": "Press tricipiti sdraiato",

  // ── M ──────────────────────────────────────────────────────────────────────
  "Machine Bench Press": "Panca alla macchina",
  "Machine Bicep Curl": "Curl bicipiti alla macchina",
  "Machine Preacher Curls": "Curl al banco scott alla macchina",
  "Machine Shoulder (Military) Press": "Press militare alla macchina",
  "Machine Triceps Extension": "Estensione tricipiti alla macchina",
  "Medicine Ball Chest Pass": "Passaggio petto con palla medica",
  "Medicine Ball Full Twist": "Torsione completa con palla medica",
  "Medicine Ball Scoop Throw": "Lancio a paletta con palla medica",
  "Middle Back Shrug": "Scrollata di spalle per la schiena media",
  "Mixed Grip Chin": "Trazioni presa mista",
  "Monster Walk": "Monster walk",
  "Mountain Climbers": "Mountain climber",
  "Muscle Snatch": "Muscle snatch",
  "Muscle Up": "Muscle-up",

  // ── N ──────────────────────────────────────────────────────────────────────
  "Narrow Stance Hack Squats": "Hack squat passo stretto",
  "Narrow Stance Leg Press": "Leg press passo stretto",
  "Narrow Stance Squats": "Squat passo stretto",
  "Natural Glute Ham Raise": "Glutei-femorali naturali",

  // ── O ──────────────────────────────────────────────────────────────────────
  "Oblique Crunches": "Crunch obliqui",
  "Oblique Crunches - On The Floor": "Crunch obliqui a terra",
  "Olympic Squat": "Squat olimpico",
  "One Arm Chin-Up": "Trazione monobraccio presa supina",
  "One Arm Dumbbell Bench Press": "Panca piana monobraccio con manubrio",
  "One Arm Dumbbell Preacher Curl": "Curl al banco scott monobraccio con manubrio",
  "One Arm Floor Press": "Press a terra monobraccio",
  "One Arm Lat Pulldown": "Lat machine monobraccio",
  "One Arm Pronated Dumbbell Triceps Extension": "Estensione tricipiti pronata monobraccio con manubrio",
  "One Arm Supinated Dumbbell Triceps Extension": "Estensione tricipiti supinata monobraccio con manubrio",
  "One Leg Barbell Squat": "Squat monopodalico con bilanciere",
  "One-Arm Dumbbell Row": "Remata monobraccio con manubrio",
  "One-Arm Flat Bench Dumbbell Flye": "Croci monobraccio su panca piana con manubrio",
  "One-Arm High-Pulley Cable Side Bends": "Flessione laterale al cavo alto monobraccio",
  "One-Arm Incline Lateral Raise": "Alzata laterale inclinata monobraccio",
  "One-Arm Kettlebell Clean": "Clean monobraccio con kettlebell",
  "One-Arm Kettlebell Clean and Jerk": "Clean and jerk monobraccio con kettlebell",
  "One-Arm Kettlebell Floor Press": "Press a terra monobraccio con kettlebell",
  "One-Arm Kettlebell Jerk": "Jerk monobraccio con kettlebell",
  "One-Arm Kettlebell Military Press To The Side": "Press militare laterale monobraccio con kettlebell",
  "One-Arm Kettlebell Para Press": "Para press monobraccio con kettlebell",
  "One-Arm Kettlebell Push Press": "Push press monobraccio con kettlebell",
  "One-Arm Kettlebell Row": "Remata monobraccio con kettlebell",
  "One-Arm Kettlebell Snatch": "Snatch monobraccio con kettlebell",
  "One-Arm Kettlebell Split Jerk": "Split jerk monobraccio con kettlebell",
  "One-Arm Kettlebell Split Snatch": "Split snatch monobraccio con kettlebell",
  "One-Arm Kettlebell Swings": "Swing monobraccio con kettlebell",
  "One-Arm Long Bar Row": "Remata monobraccio con bilanciere lungo",
  "One-Arm Medicine Ball Slam": "Slam monobraccio con palla medica",
  "One-Arm Open Palm Kettlebell Clean": "Clean a palmo aperto monobraccio con kettlebell",
  "One-Arm Overhead Kettlebell Squats": "Squat overhead monobraccio con kettlebell",
  "One-Arm Side Deadlift": "Stacco laterale monobraccio",
  "One-Arm Side Laterals": "Alzata laterale monobraccio",
  "One-Legged Cable Kickback": "Kickback monopodalico al cavo",
  "Open Palm Kettlebell Clean": "Clean a palmo aperto con kettlebell",
  "Overhead Cable Curl": "Curl al cavo overhead",
  "Overhead Slam": "Slam overhead",
  "Overhead Squat": "Squat overhead",
  "Overhead Triceps": "Estensione tricipiti overhead",

  // ── P ──────────────────────────────────────────────────────────────────────
  "Pallof Press": "Pallof press",
  "Pallof Press With Rotation": "Pallof press con rotazione",
  "Palms-Down Dumbbell Wrist Curl Over A Bench": "Curl polso con manubri palmi verso il basso su panca",
  "Palms-Down Wrist Curl Over A Bench": "Curl polso palmi verso il basso su panca",
  "Palms-Up Barbell Wrist Curl Over A Bench": "Curl polso con bilanciere palmi verso l'alto su panca",
  "Palms-Up Dumbbell Wrist Curl Over A Bench": "Curl polso con manubri palmi verso l'alto su panca",
  "Parallel Bar Dip": "Dip alle parallele",
  "Pelvic Tilt Into Bridge": "Inclinazione pelvica a ponte",
  "Physioball Hip Bridge": "Ponte anca sul physioball",
  "Pin Presses": "Press dai pin",
  "Plank": "Plank",
  "Plate Pinch": "Pinza col disco",
  "Plate Twist": "Torsione con disco",
  "Platform Hamstring Slides": "Scivolate femorali sulla piattaforma",
  "Plie Dumbbell Squat": "Squat plié con manubrio",
  "Plyo Kettlebell Pushups": "Flessioni pliometriche con kettlebell",
  "Plyo Push-up": "Flessioni pliometriche",
  "Power Clean": "Power clean",
  "Power Clean from Blocks": "Power clean dai blocchi",
  "Power Jerk": "Power jerk",
  "Power Partials": "Power partials",
  "Power Snatch": "Power snatch",
  "Power Snatch from Blocks": "Power snatch dai blocchi",
  "Power Stairs": "Scalini di potenza",
  "Preacher Curl": "Curl al banco scott",
  "Preacher Hammer Dumbbell Curl": "Curl a martello al banco scott con manubri",
  "Press Sit-Up": "Sit-up con press",
  "Pull Through": "Pull through",
  "Pullups": "Trazioni",
  "Push Press": "Push press",
  "Push Press - Behind the Neck": "Push press dietro il collo",
  "Push Up to Side Plank": "Flessione verso plank laterale",
  "Push-Up Wide": "Flessioni presa larga",
  "Push-Ups - Close Triceps Position": "Flessioni posizione stretta tricipiti",
  "Push-Ups With Feet Elevated": "Flessioni con piedi elevati",
  "Push-Ups With Feet On An Exercise Ball": "Flessioni con piedi sulla palla fitness",
  "Pushups": "Flessioni",
  "Pushups (Close and Wide Hand Positions)": "Flessioni (posizioni presa stretta e larga)",
  "Pyramid": "Piramide",

  // ── R ──────────────────────────────────────────────────────────────────────
  "Rack Pull with Bands": "Rack pull con elastici",
  "Rack Pulls": "Rack pull",
  "Rear Leg Raises": "Alzata gambe posteriore",
  "Recumbent Bike": "Cyclette reclinata",
  "Reverse Band Bench Press": "Panca piana con elastici inversi",
  "Reverse Band Box Squat": "Box squat con elastici inversi",
  "Reverse Band Deadlift": "Stacco con elastici inversi",
  "Reverse Band Power Squat": "Power squat con elastici inversi",
  "Reverse Band Sumo Deadlift": "Sumo stacco con elastici inversi",
  "Reverse Barbell Curl": "Curl inverso con bilanciere",
  "Reverse Barbell Preacher Curls": "Curl inverso al banco scott con bilanciere",
  "Reverse Cable Curl": "Curl inverso al cavo",
  "Reverse Crunch": "Crunch inverso",
  "Reverse Flyes": "Croci inverse",
  "Reverse Flyes With External Rotation": "Croci inverse con rotazione esterna",
  "Reverse Grip Bent-Over Rows": "Remata busto inclinato presa inversa",
  "Reverse Grip Triceps Pushdown": "Tricep pushdown presa inversa",
  "Reverse Hyperextension": "Iperestensione inversa",
  "Reverse Machine Flyes": "Croci inverse alla macchina",
  "Reverse Plate Curls": "Curl inverso con disco",
  "Reverse Triceps Bench Press": "Press tricipiti inverso su panca",
  "Rickshaw Carry": "Rickshaw carry",
  "Rickshaw Deadlift": "Stacco rickshaw",
  "Ring Dips": "Dip agli anelli",
  "Rocket Jump": "Salto razzo",
  "Romanian Deadlift": "Stacco rumeno",
  "Romanian Deadlift from Deficit": "Stacco rumeno in deficit",
  "Rope Climb": "Arrampicata alla fune",
  "Rope Crunch": "Crunch con corda",
  "Rope Jumping": "Salto con la corda",
  "Rope Straight-Arm Pulldown": "Pulldown a braccia tese con corda",
  "Rowing, Stationary": "Canottaggio stazionario",
  "Running, Treadmill": "Corsa sul tapis roulant",
  "Russian Twist": "Russian twist",

  // ── S ──────────────────────────────────────────────────────────────────────
  "Sandbag Load": "Carico sacchetto di sabbia",
  "Scapular Pull-Up": "Trazione scapolare",
  "Scissor Kick": "Calci a forbice",
  "Scissors Jump": "Salto a forbice",
  "Seated Band Hamstring Curl": "Leg curl seduto con elastico",
  "Seated Barbell Military Press": "Press militare seduto con bilanciere",
  "Seated Barbell Twist": "Torsione seduto con bilanciere",
  "Seated Bent-Over One-Arm Dumbbell Triceps Extension": "Estensione tricipiti monobraccio con manubrio busto inclinato seduto",
  "Seated Bent-Over Rear Delt Raise": "Alzate posteriori seduto busto inclinato",
  "Seated Bent-Over Two-Arm Dumbbell Triceps Extension": "Estensione tricipiti bibraccio con manubri busto inclinato seduto",
  "Seated Cable Rows": "Remata ai cavi seduto",
  "Seated Cable Shoulder Press": "Press spalle al cavo seduto",
  "Seated Calf Raise": "Calf raise seduto",
  "Seated Close-Grip Concentration Barbell Curl": "Curl concentrato presa stretta con bilanciere seduto",
  "Seated Dumbbell Curl": "Curl con manubri seduto",
  "Seated Dumbbell Inner Biceps Curl": "Curl bicipiti interni con manubri seduto",
  "Seated Dumbbell Palms-Down Wrist Curl": "Curl polso con manubri palmi verso il basso seduto",
  "Seated Dumbbell Palms-Up Wrist Curl": "Curl polso con manubri palmi verso l'alto seduto",
  "Seated Dumbbell Press": "Press con manubri seduto",
  "Seated Flat Bench Leg Pull-In": "Pull-in gambe su panca piana seduto",
  "Seated Good Mornings": "Good morning seduto",
  "Seated Leg Curl": "Leg curl seduto",
  "Seated Leg Tucks": "Raccolta gambe seduto",
  "Seated One-Arm Dumbbell Palms-Down Wrist Curl": "Curl polso monobraccio con manubrio palmi verso il basso seduto",
  "Seated One-Arm Dumbbell Palms-Up Wrist Curl": "Curl polso monobraccio con manubrio palmi verso l'alto seduto",
  "Seated One-arm Cable Pulley Rows": "Remata monobraccio al cavo seduto",
  "Seated Palm-Up Barbell Wrist Curl": "Curl polso con bilanciere palmi verso l'alto seduto",
  "Seated Palms-Down Barbell Wrist Curl": "Curl polso con bilanciere palmi verso il basso seduto",
  "Seated Side Lateral Raise": "Alzata laterale seduto",
  "Seated Triceps Press": "Press tricipiti seduto",
  "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl": "Curl polso bibraccio al cavo basso palmi verso l'alto seduto",
  "See-Saw Press (Alternating Side Press)": "See-saw press (press laterale alternato)",
  "Shotgun Row": "Shotgun row",
  "Shoulder Raise": "Alzata spalle",
  "Side Bridge": "Ponte laterale",
  "Side Jackknife": "Jackknife laterale",
  "Side Lateral Raise": "Alzata laterale",
  "Side Laterals to Front Raise": "Alzata laterale verso frontale",
  "Side Leg Raises": "Alzata gambe laterale",
  "Side To Side Chins": "Trazioni laterali alternati",
  "Side to Side Box Shuffle": "Box shuffle laterale",
  "Single Dumbbell Raise": "Alzata monobraccio con manubrio",
  "Single Leg Butt Kick": "Calcio ai glutei monopodalico",
  "Single Leg Glute Bridge": "Ponte glutei monopodalico",
  "Single Leg Push-off": "Spinta monopodalica",
  "Single-Arm Cable Crossover": "Crossover monobraccio al cavo",
  "Single-Arm Linear Jammer": "Jammer lineare monobraccio",
  "Single-Arm Push-Up": "Flessioni monobraccio",
  "Single-Leg High Box Squat": "Squat su box alto monopodalico",
  "Single-Leg Hop Progression": "Progressione di salti monopodalici",
  "Single-Leg Lateral Hop": "Salto laterale monopodalico",
  "Single-Leg Leg Extension": "Leg extension monopodalica",
  "Single-Leg Stride Jump": "Salto in stride monopodalico",
  "Sit Squats": "Sit squat",
  "Sit-Up": "Sit-up",
  "Skating": "Pattinaggio",
  "Sled Drag - Harness": "Trascinamento slitta con imbracatura",
  "Sled Overhead Backward Walk": "Cammino all'indietro con slitta overhead",
  "Sled Overhead Triceps Extension": "Estensione tricipiti overhead con slitta",
  "Sled Push": "Spinta slitta",
  "Sled Reverse Flye": "Croci inverse con slitta",
  "Sled Row": "Remata con slitta",
  "Sledgehammer Swings": "Oscillazioni con mazza",
  "Smith Incline Shoulder Raise": "Alzata spalle inclinata alla Smith machine",
  "Smith Machine Behind the Back Shrug": "Scrollata di spalle dietro la schiena alla Smith machine",
  "Smith Machine Bench Press": "Panca piana alla Smith machine",
  "Smith Machine Bent Over Row": "Remata busto inclinato alla Smith machine",
  "Smith Machine Calf Raise": "Calf raise alla Smith machine",
  "Smith Machine Close-Grip Bench Press": "Panca piana presa stretta alla Smith machine",
  "Smith Machine Decline Press": "Press declinato alla Smith machine",
  "Smith Machine Hang Power Clean": "Hang power clean alla Smith machine",
  "Smith Machine Hip Raise": "Alzata anca alla Smith machine",
  "Smith Machine Incline Bench Press": "Panca inclinata alla Smith machine",
  "Smith Machine Leg Press": "Leg press alla Smith machine",
  "Smith Machine One-Arm Upright Row": "Remata verticale monobraccio alla Smith machine",
  "Smith Machine Overhead Shoulder Press": "Press spalle overhead alla Smith machine",
  "Smith Machine Pistol Squat": "Pistol squat alla Smith machine",
  "Smith Machine Reverse Calf Raises": "Calf raise inverso alla Smith machine",
  "Smith Machine Squat": "Squat alla Smith machine",
  "Smith Machine Stiff-Legged Deadlift": "Stacco a gambe tese alla Smith machine",
  "Smith Machine Upright Row": "Remata verticale alla Smith machine",
  "Smith Single-Leg Split Squat": "Squat split monopodalico alla Smith machine",
  "Snatch": "Strappo",
  "Snatch Balance": "Snatch balance",
  "Snatch Deadlift": "Stacco per lo strappo",
  "Snatch Pull": "Snatch pull",
  "Snatch Shrug": "Scrollata di spalle per lo strappo",
  "Snatch from Blocks": "Strappo dai blocchi",
  "Speed Band Overhead Triceps": "Estensione tricipiti overhead veloce con elastico",
  "Speed Box Squat": "Box squat veloce",
  "Speed Squats": "Squat veloci",
  "Spell Caster": "Spell caster",
  "Spider Crawl": "Arrampicata del ragno",
  "Spider Curl": "Spider curl",
  "Split Clean": "Split clean",
  "Split Jerk": "Split jerk",
  "Split Jump": "Salto split",
  "Split Snatch": "Split snatch",
  "Split Squat with Dumbbells": "Squat split con manubri",
  "Split Squats": "Squat split",
  "Squat Jerk": "Squat jerk",
  "Squat with Bands": "Squat con elastici",
  "Squat with Chains": "Squat con catene",
  "Squat with Plate Movers": "Squat con dischi scorrevoli",
  "Squats - With Bands": "Squat con elastici",
  "Stairmaster": "Stairmaster",
  "Standing Alternating Dumbbell Press": "Press con manubri alternato in piedi",
  "Standing Barbell Calf Raise": "Calf raise in piedi con bilanciere",
  "Standing Barbell Press Behind Neck": "Press dietro il collo con bilanciere in piedi",
  "Standing Bent-Over One-Arm Dumbbell Triceps Extension": "Estensione tricipiti monobraccio busto inclinato in piedi con manubrio",
  "Standing Bent-Over Two-Arm Dumbbell Triceps Extension": "Estensione tricipiti bibraccio busto inclinato in piedi con manubri",
  "Standing Biceps Cable Curl": "Curl bicipiti al cavo in piedi",
  "Standing Bradford Press": "Bradford press in piedi",
  "Standing Cable Chest Press": "Press petto al cavo in piedi",
  "Standing Cable Lift": "Sollevamento al cavo in piedi",
  "Standing Cable Wood Chop": "Wood chop al cavo in piedi",
  "Standing Calf Raises": "Calf raise in piedi",
  "Standing Concentration Curl": "Curl concentrato in piedi",
  "Standing Dumbbell Calf Raise": "Calf raise in piedi con manubri",
  "Standing Dumbbell Press": "Press con manubri in piedi",
  "Standing Dumbbell Reverse Curl": "Curl inverso con manubri in piedi",
  "Standing Dumbbell Straight-Arm Front Delt Raise Above Head": "Alzata frontale a braccia tese sopra la testa con manubri in piedi",
  "Standing Dumbbell Triceps Extension": "Estensione tricipiti con manubri in piedi",
  "Standing Dumbbell Upright Row": "Remata verticale con manubri in piedi",
  "Standing Inner-Biceps Curl": "Curl bicipiti interni in piedi",
  "Standing Lateral Stretch": "Stretching laterale in piedi",
  "Standing Leg Curl": "Leg curl in piedi",
  "Standing Long Jump": "Salto in lungo da fermo",
  "Standing Low-Pulley Deltoid Raise": "Alzata deltoidi al cavo basso in piedi",
  "Standing Low-Pulley One-Arm Triceps Extension": "Estensione tricipiti monobraccio al cavo basso in piedi",
  "Standing Military Press": "Press militare in piedi",
  "Standing One-Arm Cable Curl": "Curl monobraccio al cavo in piedi",
  "Standing One-Arm Dumbbell Curl Over Incline Bench": "Curl monobraccio con manubrio su panca inclinata in piedi",
  "Standing One-Arm Dumbbell Triceps Extension": "Estensione tricipiti monobraccio con manubrio in piedi",
  "Standing Overhead Barbell Triceps Extension": "Estensione tricipiti overhead con bilanciere in piedi",
  "Standing Palm-In One-Arm Dumbbell Press": "Press monobraccio con manubrio palmo verso l'interno in piedi",
  "Standing Palms-In Dumbbell Press": "Press con manubri palmi verso l'interno in piedi",
  "Standing Palms-Up Barbell Behind The Back Wrist Curl": "Curl polso con bilanciere palmi verso l'alto dietro la schiena in piedi",
  "Standing Rope Crunch": "Crunch con corda in piedi",
  "Standing Soleus And Achilles Stretch": "Stretching soleo e tendine di Achille in piedi",
  "Standing Toe Touches": "Tocco punte dei piedi in piedi",
  "Standing Towel Triceps Extension": "Estensione tricipiti con asciugamano in piedi",
  "Standing Two-Arm Overhead Throw": "Lancio overhead bibraccio in piedi",
  "Star Jump": "Salto a stella",
  "Step Mill": "Step mill",
  "Step-up with Knee Raise": "Step-up con sollevamento ginocchio",
  "Stiff Leg Barbell Good Morning": "Good morning a gambe tese con bilanciere",
  "Stiff-Legged Barbell Deadlift": "Stacco a gambe tese con bilanciere",
  "Stiff-Legged Dumbbell Deadlift": "Stacco a gambe tese con manubri",
  "Stomach Vacuum": "Vacuum addominale",
  "Straight Bar Bench Mid Rows": "Remata media su panca con bilanciere retto",
  "Straight Raises on Incline Bench": "Alzate diritte su panca inclinata",
  "Straight-Arm Dumbbell Pullover": "Pullover con manubrio braccia tese",
  "Straight-Arm Pulldown": "Pulldown a braccia tese",
  "Sumo Deadlift": "Stacco sumo",
  "Sumo Deadlift with Bands": "Stacco sumo con elastici",
  "Sumo Deadlift with Chains": "Stacco sumo con catene",
  "Superman": "Superman",
  "Suspended Fallout": "Fallout sospeso",
  "Suspended Push-Up": "Flessioni sospese",
  "Suspended Reverse Crunch": "Crunch inverso sospeso",
  "Suspended Row": "Remata sospesa",
  "Suspended Split Squat": "Squat split sospeso",
  "Svend Press": "Svend press",

  // ── T ──────────────────────────────────────────────────────────────────────
  "T-Bar Row with Handle": "Remata T-bar con maniglia",
  "Tate Press": "Tate press",
  "Thigh Abductor": "Abduttore coscia",
  "Thigh Adductor": "Adduttore coscia",
  "Tire Flip": "Ribaltamento pneumatico",
  "Toe Touchers": "Tocco punte dei piedi",
  "Torso Rotation": "Rotazione del busto",
  "Trap Bar Deadlift": "Stacco con trap bar",
  "Tricep Dumbbell Kickback": "Kickback tricipiti con manubrio",
  "Triceps Overhead Extension with Rope": "Estensione tricipiti overhead con corda",
  "Triceps Pushdown": "Tricep pushdown",
  "Triceps Pushdown - Rope Attachment": "Tricep pushdown con corda",
  "Triceps Pushdown - V-Bar Attachment": "Tricep pushdown con V-bar",
  "Tuck Crunch": "Crunch a raccolta",
  "Two-Arm Dumbbell Preacher Curl": "Curl al banco scott bibraccio con manubri",
  "Two-Arm Kettlebell Clean": "Clean bibraccio con kettlebell",
  "Two-Arm Kettlebell Jerk": "Jerk bibraccio con kettlebell",
  "Two-Arm Kettlebell Military Press": "Press militare bibraccio con kettlebell",
  "Two-Arm Kettlebell Row": "Remata bibraccio con kettlebell",

  // ── U ──────────────────────────────────────────────────────────────────────
  "Underhand Cable Pulldowns": "Lat machine presa inversa al cavo",
  "Upright Barbell Row": "Remata verticale con bilanciere",
  "Upright Cable Row": "Remata verticale al cavo",
  "Upright Row - With Bands": "Remata verticale con elastici",

  // ── V ──────────────────────────────────────────────────────────────────────
  "V-Bar Pulldown": "Lat machine con V-bar",
  "V-Bar Pullup": "Trazioni con V-bar",
  "Vertical Swing": "Swing verticale",

  // ── W ──────────────────────────────────────────────────────────────────────
  "Walking, Treadmill": "Camminata sul tapis roulant",
  "Weighted Ball Hyperextension": "Iperestensione con palla pesata",
  "Weighted Ball Side Bend": "Flessione laterale con palla pesata",
  "Weighted Bench Dip": "Dip alla panca con carico",
  "Weighted Crunches": "Crunch con carico",
  "Weighted Jump Squat": "Jump squat con carico",
  "Weighted Pull Ups": "Trazioni con carico",
  "Weighted Sissy Squat": "Sissy squat con carico",
  "Weighted Sit-Ups - With Bands": "Sit-up con carico ed elastici",
  "Weighted Squat": "Squat con carico",
  "Wide Stance Barbell Squat": "Squat sumo con bilanciere",
  "Wide Stance Stiff Legs": "Stacco a gambe tese passo largo",
  "Wide-Grip Barbell Bench Press": "Panca piana presa larga con bilanciere",
  "Wide-Grip Decline Barbell Bench Press": "Panca declinata presa larga con bilanciere",
  "Wide-Grip Decline Barbell Pullover": "Pullover declinato presa larga con bilanciere",
  "Wide-Grip Lat Pulldown": "Lat machine presa larga",
  "Wide-Grip Pulldown Behind The Neck": "Lat machine presa larga dietro il collo",
  "Wide-Grip Rear Pull-Up": "Trazioni posteriori presa larga",
  "Wide-Grip Standing Barbell Curl": "Curl in piedi presa larga con bilanciere",
  "Windmills": "Windmill",
  "Wrist Roller": "Rullo per polsi",

  // ── Y / Z ─────────────────────────────────────────────────────────────────
  "Yoke Walk": "Yoke walk",
  "Zercher Squats": "Zercher squat",
  "Zottman Curl": "Zottman curl",
  "Zottman Preacher Curl": "Zottman curl al banco scott",
};

async function main() {
  // Carica esercizi non custom con nameIt == name (non ancora tradotti)
  const exercises = await prisma.exercise.findMany({
    where: { isCustom: false },
    select: { id: true, name: true, nameIt: true },
  });

  let updated = 0;
  let skipped = 0;
  let notFound = 0;

  for (const ex of exercises) {
    // Salta se già tradotto (nameIt diverso da name)
    if (ex.nameIt !== ex.name) {
      skipped++;
      continue;
    }

    const italian = T[ex.name];
    if (!italian) {
      notFound++;
      continue;
    }

    await prisma.exercise.update({
      where: { id: ex.id },
      data: { nameIt: italian },
    });
    updated++;

    if (updated % 50 === 0) process.stdout.write(`   ${updated} tradotti...\r`);
  }

  console.log(`\n✅ Traduzione completata:`);
  console.log(`   Tradotti:           ${updated}`);
  console.log(`   Già tradotti:       ${skipped}`);
  console.log(`   Senza traduzione:   ${notFound}`);

  if (notFound > 0) {
    console.log(`\n⚠️  Esercizi senza traduzione (usano nome inglese):`);
    for (const ex of exercises) {
      if (ex.nameIt === ex.name && !T[ex.name]) {
        console.log(`   - ${ex.name}`);
      }
    }
  }
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
